# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

on-window-detected = [
    {check-further-callbacks = true, run = ['layout floating']},
    {if.app-id = 'com.vivaldi.Vivaldi', run = ['layout tiling']},
    {if.app-name-regex-substring = 'alacritty', run = ['layout tiling']},
    {if.app-name-regex-substring = 'Slack', run = ['layout tiling', 'move-node-to-workspace slack']},
    {if.app-id = 'com.hnc.Discord', run = ['layout tiling', 'move-node-to-workspace discord']},
    {if.app-id = 'com.microsoft.rdc.macos', if.window-title-regex-substring = 'Microsoft Remote Desktop|Preferences', run = ['layout floating']},
    {if.app-id = 'com.microsoft.rdc.macos', run = ['layout tiling', 'move-node-to-workspace rdp']},
    {if.app-id = 'com.jetbrains.intellij', if.window-title-regex-substring = 'Settings|Run/Debug Configurations|Conflicts', run = ['layout floating']},
    {if.app-id = 'com.jetbrains.intellij', run = ['layout tiling', 'move-node-to-workspace idea']},
    {if.app-id = 'org.gnu.Emacs', run = ['layout tiling', 'move-node-to-workspace emacs']},
    {if.app-name-regex-substring = 'Zoom Meeting', run = ['layout tiling', 'move-node-to-workspace zoom']}]

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
#on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
#on-focus-changed = ['move-mouse window-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       1
outer.bottom =     1
outer.top =        [{ monitor.main = 0}, 0]
outer.right =      0

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/commands#layout
ctrl-l = 'layout tiles horizontal vertical'
ctrl-f = 'layout floating tiling'
ctrl-enter = 'fullscreen'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-up = 'focus up'
ctrl-left = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left'
ctrl-down = 'focus down'
ctrl-right = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-shift-up = 'move up'
ctrl-shift-left = 'move left'
ctrl-shift-down = 'move down'
ctrl-shift-right = 'move right'

ctrl-cmd-up = 'join-with up'
ctrl-cmd-left = 'join-with left'
ctrl-cmd-down = 'join-with down'
ctrl-cmd-right = 'join-with right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
cmd-ctrl-minus = 'resize smart -100'
cmd-ctrl-equal = 'resize smart +100'

cmd-ctrl-0 = 'exec-and-forget _aerospace-relative-resize half'
cmd-ctrl-1 = 'exec-and-forget _aerospace-relative-resize one_third'
cmd-ctrl-2 = 'exec-and-forget _aerospace-relative-resize two_thirds'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-keypad1 = 'workspace 1'
cmd-keypad2 = 'workspace 2-2'

ctrl-leftSquareBracket = 'workspace prev'
ctrl-rightSquareBracket = 'workspace next'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
cmd-ctrl-rightSquareBracket = 'exec-and-forget _aerospace-move-node-or-workspace.sh next'
cmd-ctrl-leftSquareBracket = 'exec-and-forget _aerospace-move-node-or-workspace.sh prev'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
cmd-ctrl-x = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

[workspace-to-monitor-force-assignment]
1 = 1
2-1 = 2
2-2 = 2
slack = 3
